-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Persons"
(
    "userId" integer NOT NULL,
    "firstName" character varying(50) NOT NULL,
    "lastName" character varying(50) NOT NULL,
    identification character varying(11) NOT NULL,
    birthdate date NOT NULL
);

COMMENT ON TABLE public."Persons"
    IS 'Base Class';

CREATE TABLE public."Users"
(
    id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    "nickName" character(50) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE public."Users"
    IS 'BaseUsers';

CREATE TABLE public."Employees"
(
    "userId" integer NOT NULL,
    "departmentId" integer(50) NOT NULL,
    salary double precision NOT NULL
);

COMMENT ON TABLE public."Employees"
    IS 'Worker';

CREATE TABLE public.jobseekers
(
    "userId" integer NOT NULL,
    "sectorId" integer NOT NULL,
    "clientId" integer NOT NULL,
    "jopPositionId" integer NOT NULL
);

COMMENT ON TABLE public.jobseekers
    IS 'jobseekers';

CREATE TABLE public."Customers"
(
    "userId" integer NOT NULL,
    "companyName" character varying(50) NOT NULL,
    "subscriberId" integer NOT NULL,
    "taxNumber" character varying(10) NOT NULL,
    "taxName" character varying(50) NOT NULL
);

ALTER TABLE public."Persons"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Employees"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."Persons" ("userId")
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY ("userId")
    REFERENCES public."Persons" ("userId")
    NOT VALID;


ALTER TABLE public."Customers"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."Users" (id)
    NOT VALID;

END;